import Vue from 'vue'
import {Row,Col,Menu,Autocomplete,Tooltip,Radio,Slider,RadioGroup,Form,FormItem,Loading,DropdownItem,Dropdown,DropdownMenu,Tag,ButtonGroup,MenuItem,Message,Table,Popover,Pagination,Card,TableColumn,Input,Button,Breadcrumb,BreadcrumbItem,Carousel,CarouselItem} from 'element-ui'

Vue.use(Row)
Vue.use(Col)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Input)
Vue.use(Button)
Vue.use(Tag)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Popover)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Card)
Vue.use(ButtonGroup)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Pagination)
Vue.use(Loading)
Vue.use(Tooltip)
Vue.use(Autocomplete)
Vue.use(Dropdown)
Vue.use(Slider)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.prototype.$message = Message